# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpage_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from processpage import Ui_mainpage


class Ui_loginpage(object):
    def yeniac(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_mainpage()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, loginpage):
        loginpage.setObjectName("loginpage")
        loginpage.resize(851, 595)
        self.widget = QtWidgets.QWidget(loginpage)
        self.widget.setGeometry(QtCore.QRect(100, 70, 681, 451))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"background-color:rgba(85, 98, 112, 255);\n"
" color:rgba(255, 255, 255, 200);\n"
"border-radius: 15px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top: 5px;\n"
"background-color:rgba(255, 107, 107, 255);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
" QPushButton#pushButton:hover{\n"
"background-color:rgba(255, 107, 107, 255);\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(350, 10, 311, 401))
        self.label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-radius:10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 381, 421))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(85, 98, 112, 255), stop:1 rgba(255,107, 107, 255));\n"
"border-radius:25px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(470, 30, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.yonetici_id_texti = QtWidgets.QLineEdit(self.widget)
        self.yonetici_id_texti.setGeometry(QtCore.QRect(420, 110, 221, 31))
        self.yonetici_id_texti.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;")
        self.yonetici_id_texti.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.yonetici_id_texti.setDragEnabled(False)
        self.yonetici_id_texti.setObjectName("yonetici_id_texti")
        self.yonetici_sifre_texti = QtWidgets.QLineEdit(self.widget)
        self.yonetici_sifre_texti.setGeometry(QtCore.QRect(420, 200, 221, 31))
        self.yonetici_sifre_texti.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;")
        self.yonetici_sifre_texti.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.yonetici_sifre_texti.setDragEnabled(False)
        self.yonetici_sifre_texti.setObjectName("yonetici_sifre_texti")
        self.yoneticigiris_butonu = QtWidgets.QPushButton(self.widget)
        self.yoneticigiris_butonu.setGeometry(QtCore.QRect(460, 290, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        font.setItalic(True)
        font.setUnderline(False)
        self.yoneticigiris_butonu.setFont(font)
        self.yoneticigiris_butonu.setStyleSheet("background-color:rgba(255,107,107,255);\n"
"border-radius:20px;")
        self.yoneticigiris_butonu.setObjectName("yoneticigiris_butonu")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(110, 0, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(30)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(-10, 210, 421, 211))
        font = QtGui.QFont()
        font.setPointSize(143)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgba(255,107,107,255);")
        self.label_5.setObjectName("label_5")
        self.yonetici_kayit_butonu = QtWidgets.QPushButton(self.widget)
        self.yonetici_kayit_butonu.setGeometry(QtCore.QRect(280, 350, 101, 31))
        self.yonetici_kayit_butonu.setObjectName("yonetici_kayit_butonu")
        self.yonetici_kayit_butonu.clicked.connect(self.yeniac)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 60, 291, 31))
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"")
        self.yoneticigiris_butonu.clicked.connect(self.yeniac)


        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 120, 291, 31))
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 180, 291, 31))
        self.lineEdit_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 240, 291, 31))
        self.lineEdit_4.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 300, 291, 31))
        self.lineEdit_5.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,200);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.retranslateUi(loginpage)
        QtCore.QMetaObject.connectSlotsByName(loginpage)

    def retranslateUi(self, loginpage):
        _translate = QtCore.QCoreApplication.translate
        loginpage.setWindowTitle(_translate("loginpage", "Form"))
        self.label_3.setText(_translate("loginpage", "LOG IN"))
        self.yonetici_id_texti.setPlaceholderText(_translate("loginpage", "NAME"))
        self.yonetici_sifre_texti.setPlaceholderText(_translate("loginpage", "PASSWORD"))
        self.yoneticigiris_butonu.setText(_translate("loginpage", "LOG IN"))

        self.label_4.setText(_translate("loginpage", "SİGN UP"))
        self.label_5.setText(_translate("loginpage", "🗻"))
        self.yonetici_kayit_butonu.setText(_translate("loginpage", "SİGN UP"))
        self.lineEdit.setPlaceholderText(_translate("loginpage", "NAME"))
        self.lineEdit_2.setPlaceholderText(_translate("loginpage", "SURNAME"))
        self.lineEdit_3.setPlaceholderText(_translate("loginpage", "ID"))
        self.lineEdit_4.setPlaceholderText(_translate("loginpage", "CITY WHERE HE WORKS"))
        self.lineEdit_5.setPlaceholderText(_translate("loginpage", "PASSWORD"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginpage = QtWidgets.QWidget()
    ui = Ui_loginpage()
    ui.setupUi(loginpage)
    loginpage.show()
    sys.exit(app.exec_())
